//Note - AI assistance
// I use Claude to help to debug
// No code was copied blindly
// All suggestions were reviewed, adapted and tested
// The logo is generated by the AI (Google Gemini)

package com.chong.s34598162.medtrack

import android.content.Context
import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.lifecycleScope
import com.chong.s34598162.medtrack.data.DatabseSeeder
import com.chong.s34598162.medtrack.data.MedTrackDatabase
import com.chong.s34598162.medtrack.ui.theme.MedtrackTheme
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val database = MedTrackDatabase.getDatabase(this)
        lifecycleScope.launch (Dispatchers.IO) {
            DatabseSeeder.seedIfNeeded(this@MainActivity, database)
        }

        // try to retrieve saved patient id, if nothing save, set as empty
        val sharePref = getSharedPreferences("MedTrackPref", Context.MODE_PRIVATE)
        val patientID = sharePref.getString("logged_in_patient_id", "") ?: ""

        // If there is patient id save, direct to home screen
        if (patientID.isNotEmpty()) {
            startActivity(Intent(this, HomeActivity::class.java))
            finish()
            return
        }
        enableEdgeToEdge()
        setContent {
            MedtrackTheme {
                val uriHandler = LocalUriHandler.current // handle url opening
                val context = LocalContext.current

                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    Column(modifier = Modifier.padding(innerPadding)
                        .padding(16.dp).fillMaxSize(),
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.Center
                    ) {
                        //Add logo at the top
                        Image(
                            painter = painterResource(id = R.drawable.medtracklogoupdown),
                            contentDescription = "Logo Image",
                            modifier = Modifier.fillMaxWidth()
                                .size(250.dp)
                                .padding(16.dp)
                        )

                        Spacer(modifier = Modifier.height(32.dp))

                        // Title
                        Text(text = "Welcome to MedTrack!",
                            style = TextStyle(
                                fontWeight = FontWeight.Bold,
                                fontSize = 30.sp,
                                textAlign = TextAlign.Center
                            )
                        )

                        Spacer(modifier = Modifier.height(16.dp))

                        // Health disclaimer text
                        Text(text = "This app is for tracking purposes only and does not " +
                                "replace professional medical advice.",
                            style = TextStyle(
                                fontSize = 16.sp,
                                textAlign = TextAlign.Center,
                                color = Color.Gray
                            ),
                            modifier = Modifier.padding(horizontal = 40.dp)
                        )

                        Spacer(modifier = Modifier.height(16.dp))

                        // Link that open clinic website
                        Row(
                            modifier = Modifier.padding( top = 16.dp)
                                .clickable{
                                    uriHandler.openUri("https://monashhealth.org/services/nephrology/clinics/")
                                },
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.Center
                        ) {
                            Text(
                                text = "visit Monash Health Clinic",
                                style = TextStyle(
                                    color = Color.Blue,
                                    textDecoration = TextDecoration.Underline,
                                    fontSize = 16.sp
                                )
                            )
                        }

                        Spacer(modifier = Modifier.height(16.dp))

                        // ID and name
                        Text(text = "ID: 34598162 Chong Jia Xuan")

                        Spacer(modifier = Modifier.height(32.dp))
                        // Login Button
                        Button(
                            onClick = {
                                context.startActivity(Intent(context, LoginScreenActivity::class.java))
                            },
                            modifier = Modifier.fillMaxWidth(),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = Color(0xFF1A1A40),
                                contentColor = Color.White
                            )
                        ) {
                            Text("LOGIN", fontWeight = FontWeight.Bold)
                        }

                        Spacer(modifier = Modifier.height(16.dp))
                        // Sign up button
                        Button(
                            onClick = {
                                context.startActivity(Intent(context, SignUpScreenActivity::class.java))
                            },
                            modifier = Modifier.fillMaxWidth(),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = Color.White,
                                contentColor = Color.Black
                            )
                        ) {
                            Text("SIGN UP", fontWeight = FontWeight.Bold)
                        }


                    }
                }
            }
        }
    }
}

